from enum import Enum


class VoiceState(str, Enum):
    SPEECH_STARTED = "SPEECH_STARTED"
    LISTENING = "LISTENING"
    TRANSCRIBING = "TRANSCRIBING"
    THINKING = "THINKING"
    SPEAKING = "SPEAKING"
    INTERRUPTED = "INTERRUPTED"
    DISCONNECTED = "DISCONNECTED"
