apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voice-ai.fullname" . }}
  labels:
    app: {{ include "voice-ai.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "voice-ai.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "voice-ai.name" . }}
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app/voiceAI
          command: ["sh", "-c", "./wait-for-it.sh {{ .Values.env.POSTGRES_HOST }}:{{ .Values.env.POSTGRES_PORT }} --strict --timeout=60 && python manage.py migrate --noinput"]
          env:
            {{- range $key, $value := .Values.env}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      containers:
        - name: voice-ai-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app/voiceAI
          command: ["sh", "-c", "./k8s-start.sh"]
          env: 
            {{- range $key, $value := .Values.env}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: voice-ai
            initialDelaySeconds: 10
            periodSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voice-ai-grpc.fullname" . }}
  labels:
    app: {{ include "voice-ai-grpc.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "voice-ai-grpc.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "voice-ai-grpc.name" . }}
    spec:
      containers:
        - name: voice-ai-grpc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app/voiceAI
          command: ["sh", "-c", "./wait-for-it.sh {{ .Values.env.RABBITMQ_HOST }}:5672 --strict --timeout=120 &&./grpc-start.sh"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 50051
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voice-ai.fullname" . }}-celery-tts
  labels:
    app: {{ include "voice-ai.name" . }}-celery-tts
spec:
  replicas: {{ .Values.celeryTTS.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "voice-ai.name" . }}-celery-tts
  template:
    metadata:
      labels:
        app: {{ include "voice-ai.name" . }}-celery-tts
    spec:
      containers:
        - name: celery-tts
          image: "{{ .Values.celeryTTS.image.repository }}:{{ .Values.celeryTTS.image.tag }}"
          imagePullPolicy: {{ .Values.celeryTTS.image.pullPolicy }}
          workingDir: /app/voiceAI
          command:
            - "sh"
            - "-c"
            - >
              export GROQ_API_KEY=$(grep '^GROQ_API_KEY=' /app/.env.docker | cut -d '=' -f2) &&
              ./wait-for-it.sh {{ .Values.celeryTTS.env.RABBITMQ_HOST }}:5672 --strict --timeout=120 &&
              celery -A app.common.celery:celery_app worker -l info -Q {{ join "," .Values.celeryTTS.worker.queues }} --concurrency={{ .Values.celeryTTS.worker.concurrency }} --prefetch-multiplier=1 --max-tasks-per-child=50
          env:
            {{- range $key, $value := .Values.celeryTTS.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.celeryTTS.resources.requests.cpu }}
              memory: {{ .Values.celeryTTS.resources.requests.memory }}
            limits:
              cpu: {{ .Values.celeryTTS.resources.limits.cpu }}
              memory: {{ .Values.celeryTTS.resources.limits.memory }}
          volumeMounts:
            - name: xtts-model
              mountPath: /app/models/xtts
      volumes:
        - name: xtts-model
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaim.name }}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voice-ai.fullname" . }}-celery-audio
  labels:
    app: {{ include "voice-ai.name" . }}-celery-audio
spec:
  replicas: {{ .Values.celeryAudio.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "voice-ai.name" . }}-celery-audio
  template:
    metadata:
      labels:
        app: {{ include "voice-ai.name" . }}-celery-audio
    spec:
      containers:
        - name: celery-audio
          image: "{{ .Values.celeryAudio.image.repository }}:{{ .Values.celeryAudio.image.tag }}"
          imagePullPolicy: {{ .Values.celeryAudio.image.pullPolicy }}
          workingDir: /app/voiceAI
          command:
            - "sh"
            - "-c"
            - >
              export GROQ_API_KEY=$(grep '^GROQ_API_KEY=' /app/.env.docker | cut -d '=' -f2) &&
              ./wait-for-it.sh {{ .Values.celeryAudio.env.RABBITMQ_HOST }}:5672 --strict --timeout=120 &&
              celery -A app.common.celery:celery_app worker -l info -Q {{ join "," .Values.celeryAudio.worker.queues }} --concurrency={{ .Values.celeryAudio.worker.concurrency }} --prefetch-multiplier=1 --max-tasks-per-child=50
          env:
            {{- range $key, $value := .Values.celeryAudio.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.celeryAudio.resources.requests.cpu }}
              memory: {{ .Values.celeryAudio.resources.requests.memory }}
            limits:
              cpu: {{ .Values.celeryAudio.resources.limits.cpu }}
              memory: {{ .Values.celeryAudio.resources.limits.memory }}
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "voice-ai-audio-worker.fullname" . }}
#   labels:
#     app: {{ include "voice-ai-audio-worker.name" . }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: {{ include "voice-ai-audio-worker.name" . }}
#   template:
#     metadata:
#       labels:
#         app: {{ include "voice-ai-audio-worker.name" . }}
#     spec:
#       containers:
#         - name: voice-ai-audio-worker
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           workingDir: /app/voiceAI
#           command:
#           - "sh"
#           - "-c"
#           - >
#             export GROQ_API_KEY=$(grep '^GROQ_API_KEY=' /app/.env.docker | cut -d '=' -f2) &&
#             ./wait-for-it.sh {{ .Values.env.RABBITMQ_HOST }}:5672 --strict --timeout=120 &&
#             python -m app.workers.task_audio
#           env:
#             {{- range $key, $value := .Values.env }}
#             {{- if $value }}
#             - name: {{ $key }}
#               value: {{ $value | quote }}
#             {{- end }}
#             {{- end }}
#       restartPolicy: Always
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "voice-ai-tts-worker.fullname" . }}
#   labels:
#     app: {{ include "voice-ai-tts-worker.name" . }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: {{ include "voice-ai-tts-worker.name" . }}
#   template:
#     metadata:
#       labels:
#         app: {{ include "voice-ai-tts-worker.name" . }}
#     spec:
#       containers:
#         - name: voice-ai-tts-worker
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           workingDir: /app/voiceAI
#           command:
#             - "sh"
#             - "-c"
#             - >
#               export GROQ_API_KEY=$(grep '^GROQ_API_KEY=' /app/.env.docker | cut -d '=' -f2) &&
#               ./wait-for-it.sh {{ .Values.env.RABBITMQ_HOST }}:5672 --strict --timeout=120 &&
#               python -m app.workers.task_tts
#           env:
#             {{- range $key, $value := .Values.env }}
#             {{- if $value }}
#             - name: {{ $key }}
#               value: {{ $value | quote }}
#             {{- end }}
#             {{- end }}
#           volumeMounts:
#             - name: xtts-model
#               mountPath: /app/models
#           resources:
#             requests:
#               cpu: "500m"
#               memory: "1Gi"
#             limits:
#               cpu: "1000m"
#               memory: "2Gi"

#       volumes:
#         - name: xtts-model
#           persistentVolumeClaim:
#             claimName: {{ .Values.volumeClaim.name }}

#       restartPolicy: Always